### ISSUE TITLE
Where can I find FB15k_Entity_Type_%s.txt?

### ISSUE THREAD

**Issue by liaopeiyuan** [joeybose/Flexible-Fairness-Constraints#2]
I tried to reproduce your FB15k experiments but was never able to generate the data needed. It seems that FB15k_Entity_Type_%s.txt is some special text file not included in the official dataset. Is there a separate website where I can obtain the file, or is there another script I should download to generate this? Thanks!

**Comment by joeybose** [comment]
You can use this repo: https://github.com/cmoon2/knowledge_graph to get the FB15k entity dataset.

**Comment by liaopeiyuan** [comment]
Thanks!! I'll try to see if this works.
