### ISSUE TITLE
Inquiry about the mean rank results reported in the paper

### ISSUE THREAD

**Issue by liaopeiyuan** [joeybose/Flexible-Fairness-Constraints#4]
Hi! I was just trying to reproduce the paper's result on FB15K-237 and on Comet.ml I observed that the training mean-rank keeps increasing and reached around 860. How shall I interpret the result with regards to what's reported in the paper?

**Comment by joeybose** [comment]
Can you provide more details on which model/hyperparameters you're using? Note that the adversarial weight would greatly affect the mean rank ---i.e. enforcing higher fairness usually leads to worse utility in the main task.

**Comment by liaopeiyuan** [comment]
I realized that I used the wrong adversarial weight. Thank you very much!
