### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [*size*,*size*] is at version 3; expected version 2 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

### ISSUE THREAD

**Issue by deancochran** [joeybose/Flexible-Fairness-Constraints#8]
Hello,

(Scenario: Trying to verify the MovieLens dataset results)

There seem to be some gradient computation issues with your repo. Specifically, way in which the TransD_movielens.py graidents are created seem to be incorrect. See [relevant findings](https://github.com/pytorch/pytorch/issues/39141). 

I find that the error seems to be inside the train_gcmc function when back-propagating for each discriminator model.

PyTorch 1.4 does not show this error, PyTorch 1.5 and above does.

**Comment by joeybose** [comment]
Hi, this is a known issue. As this paper was published a while back issues on newer versions of Pytorch can happen. There is no plan to update this codebase to more modern versions though so I encourage you to use the older versions if you need to reproduce results.

**Comment by deancochran** [comment]
Thanks for the help. You're saving me more time than you can ever imagine.
